name: Test and build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"
      - name: Install fonts
        run: sudo apt update && sudo apt install -y fonts-nanum fonts-nanum-coding
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Monolith
        run: cargo install monolith
      - name: Inject assets
        run: cp -r assets _site
      - name: Build README.md to HTML
        run: pandoc -s -f gfm -o README.html --css assets/pandoc.css --include-before-body assets/body-before.txt --include-after-body assets/body-after.txt README.md
      - name: Bundle README.md
        run: monolith -o _site/README.html README.html
      - name: Build README.html to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: _site/README.html
          outputFile: _site/README.pdf
          pdfOptions: '{"format":"A4"}'
      - name: Build PORTFOLIO-OSS-KO.md to PDF
        run: pandoc -s --pdf-engine tectonic -o _site/PORTFOLIO-OSS-KO.pdf PORTFOLIO-OSS-KO.md
      - name: Inject LICENSE
        run: cp LICENSE _site/LICENSE
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
